12

머신러닝을 시작합니다!

#머신러닝을 시작합니다!

In [7]:
a= [1,2,3,4,5]
a[4] = 'young'
print(a)
b = list(range(10))
c = list(b)
print(c)

[1, 2, 3, 4, 'young']
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
a=(1,2,3)
print(a)
print(type(a))

(1, 2, 3)
<class 'tuple'>


In [11]:
num = [2,4,6,7,8]
for i in range(len(num)):
    num[i] = num[i]*2
print(num)

[4, 8, 12, 14, 16]


In [9]:
import numpy as np
x = np.array([1,2,3])
print(x)

[1 2 3]


In [13]:
print(x)

[1 2 3]


In [17]:
import numpy as np
x = np.array([1,2,3,4,5,6])
print(x)
print(x.shape)
x = x.reshape((2,3))
print(x)
print(x.shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [19]:
v = np.array([[1,2,3],[4,5,6]])
w = np.array([[1,1],[2,2],[3,3]])
print(v.dot(w))


[[14 14]
 [32 32]]


In [24]:
print(x[:1,:])

[[1 2 3]]


In [25]:
x > 3

array([[False, False, False],
       [ True,  True,  True]])

In [28]:
x[x>2] = 100

In [32]:
print(x)

[[  1   2 100]
 [100 100 100]]


In [33]:
x[x>2]

array([100, 100, 100, 100])

In [46]:
def my_func1(D):
    m = np.mean(D)
    s = np.std(D)
    return m,s
data = np.random.randint(1000,2000,10)
d_mean, d_std = my_func1(data)
print('mean:{0:3.2f}, std:{1:3.2f}'.format(d_mean, d_std))

mean:1479.30, std:251.54


In [49]:
print(data)

[1765 1131 1231 1662 1716 1614 1549 1417 1022 1686]


In [48]:
np.save('testData.npy', data)

In [50]:
data = []

In [51]:
data = np.load('testData.npy')

In [52]:
print(data)

[1765 1131 1231 1662 1716 1614 1549 1417 1022 1686]


In [55]:
data1 = np.random.randint(0,100,10)
data2 = np.random.randn(10)
np.savez('testRandom.npz', data1=data1, data2=data2)

In [56]:
data1 = []
ddata2 = []

In [57]:
outfile = np.load('testRandom.npz')
print(outfile.files)

['data1', 'data2']


In [58]:
data1 = outfile['data1']
data2 = outfile['data2']
print(data1)
print(data2)

[28 95 20 61 39 63 33 97 30 33]
[ 0.93243404  1.85298192  1.35048979 -0.38738398 -0.92621461 -2.39575057
 -2.38064813  1.2300303  -1.21882776 -0.09848735]
