In [2]:
import numpy as np

A=np.array([[0,0,-2],[1,2,1],[1,0,3]])
P=np.array([[-1,0,-2],[0,1,1],[1,0,1]])
invP = np.linalg.inv(P)
GamaM = invP.dot(A.dot(P))
print(GamaM)

#P행렬의 첫번째 열벡터는 고유값 2에 대한 고유벡터이다. 두번째 열벡터는 고유값 2에 대한 고유벡터이다. 
#P행렬의 세번째 열벡터는 고유값 1에 대한 고유벡터이다. 대각행렬 첫번째 대각선 성분의 값 2는 P행렬의
#첫번째 열벡터에 대한 고유값이다. 비슷하게 대각행렬 두번째 대각선 성분의 값 2는 P행렬의 두번째 
#열벡터에 대한 고유값이다. 마지작으로 대각행렬 세번째 대각선 성분의 값 1은 P행렬의 세번째 열벡터에
#고유값이다. 


[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 1.]]
